# Generated by Django 5.0 on 2023-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("age", models.IntegerField()),
                ("nationality", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
