# Generated by Django 5.0 on 2023-12-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_delete_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="slug",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
