# Generated by Django 5.0 on 2023-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
