# Generated by Django 5.0 on 2023-12-31 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_cart_count_cart_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="count",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
    ]
