# Generated by Django 5.0 on 2023-12-31 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_cart_count_remove_cart_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="slug",
        ),
    ]
