# Generated by Django 5.0 on 2024-01-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_cart_products_cartproduct_cart"),
        ("products", "0004_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cart_products",
                to="products.product",
            ),
        ),
    ]
