# Generated by Django 5.0 on 2024-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_available_product_country_product_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
